#!/usr/bin/python3
import os
import shutil
import sys
import yaml
import markdown
import re

def load_config(config_path):
    with open(config_path, 'r') as file:
        config = yaml.safe_load(file)
    return config

def convert(origin, dest_dir):
    print(f"{origin} -> {dest_dir}")
    filename = os.path.basename(origin).replace(".md", ".html")
    with open(origin, 'r') as file:
        content = file.read()

    # extracting front matter
    metadata = {}
    match = re.match(r"^---\n(.*?)\n---\n(.*)", content, re.DOTALL)
    if match:
        metadata = yaml.safe_load(match.group(1))
        metadata["date"] = metadata["date"].isoformat()
        content = match.group(2)
    else:
        metadata["title"] = "mattlozinski"
    metadata["content"] = markdown.markdown(content, extensions=['sane_lists', 'fenced_code', 'def_list'])
    temp = open("layout/single.html", "r").read()
    for exp in metadata:
        temp = temp.replace("{{ "+exp+" }}", metadata[exp])
    with open(os.path.join(dest_dir, filename), "w") as file:
        file.write(temp)
    return metadata

def gen_list(path, output_dir):
    list_name = os.path.basename(path)
    output_dir = os.path.join(output_dir, list_name)
    print(f"{list_name} (list) -> {output_dir}")
    os.mkdir(output_dir)
    for filename in os.listdir(path):
        origin = os.path.join(path, filename)
        if not os.path.isdir(origin) and origin.endswith(".md"):
            convert(origin, output_dir)

if __name__ == "__main__":

    # read config file
    config_path = "config.yaml"
    if len(sys.argv) > 1:
        config_path = sys.argv[1]
    if not os.path.isfile(config_path):
        print(f"{config_path} does not exist")
        sys.exit(1)
    config = load_config(config_path)

    # clear output dir
    try:
        os.mkdir(config["output"])
    except FileExistsError:
        shutil.rmtree(config["output"])
        os.mkdir(config["output"])

    # copy all static files to output dir
    shutil.copytree(config["static"], config["output"], dirs_exist_ok=True)

    # convert all content files
    for item in os.listdir(config["source"]):
        path = os.path.join(config["source"], item)
        if os.path.isdir(path):
            gen_list(path, config["output"])
        else:
            if path.endswith(".md"):
                convert(path, config["output"])
